export type OrderLine={sequence:number;productId:string;quantity:number;remarks:string|null};
export type SalesOrder={id:string;visitId:string;customerType:"chemist"|"stockist";customerId:string;customerCode:string;customerName:string;status:"BOOKED";lines:Array<OrderLine&{productCode:string;productName:string}>;updatedAt:string};
export type OrderRepository={save(t:string,u:string,v:string,input:{operationId:string;remarks:string|null;lines:OrderLine[]}):Promise<string>;getByVisit(t:string,v:string,token:string):Promise<SalesOrder|null>};
export class OrderInputError extends Error{};export class OrderNotFoundError extends Error{};export class OrderConflictError extends Error{};
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
function uuid(v:unknown,f:string){if(typeof v!=="string"||!UUID.test(v))throw new OrderInputError(`${f} must be a UUID`);return v}
function text(v:unknown,f:string,max:number){if(v==null||v==="")return null;if(typeof v!=="string")throw new OrderInputError(`Invalid ${f}`);const s=v.trim();if(!s||s.length>max)throw new OrderInputError(`Invalid ${f}`);return s}
function lines(v:unknown):OrderLine[]{if(!Array.isArray(v)||v.length<1||v.length>50)throw new OrderInputError("lines must contain 1 to 50 entries");const seen=new Set<string>();return v.map((raw,i)=>{if(!raw||typeof raw!=="object"||Array.isArray(raw))throw new OrderInputError(`Invalid line ${i}`);const x=raw as Record<string,unknown>;if(!Number.isInteger(x.sequence)||(x.sequence as number)<1)throw new OrderInputError("Invalid sequence");const productId=uuid(x.productId,"productId");if(seen.has(productId))throw new OrderInputError("Duplicate product");seen.add(productId);if(!Number.isInteger(x.quantity)||(x.quantity as number)<1||(x.quantity as number)>1000000)throw new OrderInputError("Invalid quantity");return{sequence:x.sequence as number,productId,quantity:x.quantity as number,remarks:text(x.remarks,"remarks",500)}}).sort((a,b)=>a.sequence-b.sequence)}
export function createOrderService(repository:OrderRepository){return{
 async save(t:string,u:string,token:string,visitValue:unknown,value:Record<string,unknown>){const visitId=uuid(visitValue,"visitId");const id=await repository.save(t,u,visitId,{operationId:uuid(value.operationId,"operationId"),remarks:text(value.remarks,"remarks",1000),lines:lines(value.lines)});const row=await repository.getByVisit(t,visitId,token);if(!row||row.id!==id)throw new OrderConflictError("Order could not be confirmed");return row;},
 async get(t:string,token:string,visitValue:unknown){const row=await repository.getByVisit(t,uuid(visitValue,"visitId"),token);if(!row)throw new OrderNotFoundError("Order not found");return row;}
};}
