begin;
insert into public.role_permissions(role_key,permission_key)values('TENANT_ADMIN','EXPENSE_VIEW_TEAM'),('TENANT_ADMIN','EXPENSE_APPROVE'),('MANAGER','EXPENSE_VIEW_TEAM'),('MANAGER','EXPENSE_APPROVE')on conflict do nothing;
create table public.expense_claims(
 id uuid primary key default extensions.gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete cascade,execution_id uuid not null,employee_id uuid not null,work_date date not null,currency_code text not null check(currency_code~'^[A-Z]{3}$'),status text not null default'DRAFT' check(status in('DRAFT','SUBMITTED','APPROVED','REJECTED','RETURNED')),total_amount numeric(14,2) not null default 0 check(total_amount>=0),submission_comment text,submitted_at timestamptz,submit_operation_id uuid,reviewed_by uuid,reviewed_at timestamptz,review_comment text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(tenant_id,id),unique(tenant_id,execution_id),unique(tenant_id,employee_id,submit_operation_id),foreign key(tenant_id,execution_id)references public.tour_executions(tenant_id,id)on delete restrict,foreign key(tenant_id,employee_id)references public.employees(tenant_id,id)on delete restrict,foreign key(tenant_id,reviewed_by)references public.tenant_memberships(tenant_id,user_id)on delete restrict);
create table public.expense_lines(id uuid primary key default extensions.gen_random_uuid(),tenant_id uuid not null,expense_claim_id uuid not null,sequence_no integer not null check(sequence_no>0),category text not null check(category in('TRAVEL','MEAL','LODGING','LOCAL_CONVEYANCE','OTHER')),amount numeric(14,2) not null check(amount>0),remarks text,receipt_reference text,unique(tenant_id,expense_claim_id,sequence_no),foreign key(tenant_id,expense_claim_id)references public.expense_claims(tenant_id,id)on delete cascade);
create table public.expense_decisions(id uuid primary key default extensions.gen_random_uuid(),tenant_id uuid not null,expense_claim_id uuid not null,actor_user_id uuid not null,decision text not null check(decision in('APPROVE','REJECT','RETURN')),comment text,created_at timestamptz not null default now(),foreign key(tenant_id,expense_claim_id)references public.expense_claims(tenant_id,id)on delete restrict,foreign key(tenant_id,actor_user_id)references public.tenant_memberships(tenant_id,user_id)on delete restrict);
create table public.expense_operations(id uuid primary key default extensions.gen_random_uuid(),tenant_id uuid not null,expense_claim_id uuid not null,actor_user_id uuid not null,operation_id uuid not null,request_hash bytea not null,created_at timestamptz not null default now(),unique(tenant_id,actor_user_id,operation_id),foreign key(tenant_id,expense_claim_id)references public.expense_claims(tenant_id,id)on delete cascade,foreign key(tenant_id,actor_user_id)references public.tenant_memberships(tenant_id,user_id)on delete restrict);
create or replace function public.admin_save_expense_claim(p_tenant_id uuid,p_user_id uuid,p_execution_id uuid,p_operation_id uuid,p_currency text,p_lines jsonb)
returns uuid language plpgsql security definer set search_path='' as $$
declare v_exec public.tour_executions%rowtype;v_owner uuid;v_claim public.expense_claims%rowtype;v_claim_id uuid;v_hash bytea;v_old bytea;v_line jsonb;v_total numeric(14,2):=0;
begin
 if p_currency!~'^[A-Z]{3}$' or jsonb_typeof(p_lines)<>'array' or jsonb_array_length(p_lines)<1 or jsonb_array_length(p_lines)>50 then raise exception'invalid expense payload';end if;
 v_hash:=extensions.digest(jsonb_build_object('executionId',p_execution_id,'currency',p_currency,'lines',p_lines)::text,'sha256');
 select operation.expense_claim_id,operation.request_hash into v_claim_id,v_old from public.expense_operations operation where operation.tenant_id=p_tenant_id and operation.actor_user_id=p_user_id and operation.operation_id=p_operation_id;
 if found then if v_old is distinct from v_hash then raise exception'idempotency key reused with different payload';end if;return v_claim_id;end if;
 select execution.* into v_exec from public.tour_executions execution where execution.tenant_id=p_tenant_id and execution.id=p_execution_id;
 select employee.user_id into v_owner from public.employees employee where employee.tenant_id=p_tenant_id and employee.id=v_exec.employee_id;
 if v_exec.id is null or v_owner is distinct from p_user_id then raise exception'owned execution not found';end if;
 select claim.* into v_claim from public.expense_claims claim where claim.tenant_id=p_tenant_id and claim.execution_id=p_execution_id for update;
 if v_claim.id is not null and v_claim.status not in('DRAFT','RETURNED')then raise exception'expense claim is not editable';end if;
 if v_claim.id is null then insert into public.expense_claims(tenant_id,execution_id,employee_id,work_date,currency_code)values(p_tenant_id,v_exec.id,v_exec.employee_id,v_exec.work_date,p_currency)returning*into v_claim;
 else update public.expense_claims set status='DRAFT',currency_code=p_currency,submission_comment=null,submitted_at=null,submit_operation_id=null,reviewed_by=null,reviewed_at=null,review_comment=null,updated_at=clock_timestamp()where tenant_id=p_tenant_id and id=v_claim.id;delete from public.expense_lines where tenant_id=p_tenant_id and expense_claim_id=v_claim.id;end if;
 for v_line in select value from jsonb_array_elements(p_lines)loop if(v_line->>'amount')::numeric<=0 then raise exception'invalid expense amount';end if;v_total:=v_total+(v_line->>'amount')::numeric;insert into public.expense_lines(tenant_id,expense_claim_id,sequence_no,category,amount,remarks,receipt_reference)values(p_tenant_id,v_claim.id,(v_line->>'sequence')::integer,v_line->>'category',(v_line->>'amount')::numeric,nullif(trim(v_line->>'remarks'),''),nullif(trim(v_line->>'receiptReference'),''));end loop;
 update public.expense_claims set total_amount=v_total where tenant_id=p_tenant_id and id=v_claim.id;insert into public.expense_operations(tenant_id,expense_claim_id,actor_user_id,operation_id,request_hash)values(p_tenant_id,v_claim.id,p_user_id,p_operation_id,v_hash);return v_claim.id;
end;$$;
create or replace function public.admin_submit_expense_claim(p_tenant_id uuid,p_user_id uuid,p_claim_id uuid,p_operation_id uuid,p_comment text)returns void language plpgsql security definer set search_path='' as $$
declare v_claim public.expense_claims%rowtype;v_owner uuid;begin select claim.* into v_claim from public.expense_claims claim where claim.tenant_id=p_tenant_id and claim.id=p_claim_id for update;if v_claim.id is null then raise exception'claim not found';end if;select user_id into v_owner from public.employees where tenant_id=p_tenant_id and id=v_claim.employee_id;if v_owner is distinct from p_user_id then raise exception'claim not owned';end if;if v_claim.status='SUBMITTED'and v_claim.submit_operation_id=p_operation_id then return;end if;if v_claim.status not in('DRAFT','RETURNED')then raise exception'claim cannot be submitted';end if;update public.expense_claims set status='SUBMITTED',submission_comment=nullif(trim(p_comment),''),submitted_at=clock_timestamp(),submit_operation_id=p_operation_id,updated_at=clock_timestamp()where tenant_id=p_tenant_id and id=p_claim_id;end;$$;
create or replace function public.admin_decide_expense_claim(p_tenant_id uuid,p_actor uuid,p_claim_id uuid,p_decision text,p_comment text)returns void language plpgsql security definer set search_path='' as $$
declare v_claim public.expense_claims%rowtype;v_employee public.employees%rowtype;v_to text;begin select claim.* into v_claim from public.expense_claims claim where claim.tenant_id=p_tenant_id and claim.id=p_claim_id for update;if v_claim.id is null or v_claim.status<>'SUBMITTED'then raise exception'submitted claim not found';end if;select employee.*into v_employee from public.employees employee where employee.tenant_id=p_tenant_id and employee.id=v_claim.employee_id;if v_employee.user_id=p_actor then raise exception'self approval not allowed';end if;if not public.user_has_permission(p_tenant_id,p_actor,'EXPENSE_APPROVE',v_employee.org_unit_id)then raise exception'expense approval denied';end if;if p_decision='APPROVE'then v_to:='APPROVED';elsif p_decision='REJECT'then v_to:='REJECTED';elsif p_decision='RETURN'then v_to:='RETURNED';else raise exception'invalid decision';end if;if p_decision<>'APPROVE'and nullif(trim(p_comment),'')is null then raise exception'comment required';end if;update public.expense_claims set status=v_to,reviewed_by=p_actor,reviewed_at=clock_timestamp(),review_comment=nullif(trim(p_comment),''),updated_at=clock_timestamp()where tenant_id=p_tenant_id and id=p_claim_id;insert into public.expense_decisions(tenant_id,expense_claim_id,actor_user_id,decision,comment)values(p_tenant_id,p_claim_id,p_actor,p_decision,nullif(trim(p_comment),''));end;$$;
revoke all on function public.admin_save_expense_claim(uuid,uuid,uuid,uuid,text,jsonb)from public;revoke all on function public.admin_submit_expense_claim(uuid,uuid,uuid,uuid,text)from public;revoke all on function public.admin_decide_expense_claim(uuid,uuid,uuid,text,text)from public;grant execute on function public.admin_save_expense_claim(uuid,uuid,uuid,uuid,text,jsonb)to service_role;grant execute on function public.admin_submit_expense_claim(uuid,uuid,uuid,uuid,text)to service_role;grant execute on function public.admin_decide_expense_claim(uuid,uuid,uuid,text,text)to service_role;
alter table public.expense_claims enable row level security;alter table public.expense_lines enable row level security;alter table public.expense_decisions enable row level security;alter table public.expense_operations enable row level security;revoke all on public.expense_claims from anon,authenticated;revoke all on public.expense_lines from anon,authenticated;revoke all on public.expense_decisions from anon,authenticated;revoke all on public.expense_operations from anon,authenticated;grant select on public.expense_claims to authenticated;grant select on public.expense_lines to authenticated;grant select on public.expense_decisions to authenticated;
create policy expense_claims_owner_or_team on public.expense_claims for select to authenticated using(exists(select 1 from public.employees employee where employee.tenant_id=expense_claims.tenant_id and employee.id=expense_claims.employee_id and(employee.user_id=auth.uid()or public.has_permission(expense_claims.tenant_id,'EXPENSE_VIEW_TEAM',employee.org_unit_id))));
create policy expense_lines_visible on public.expense_lines for select to authenticated using(exists(select 1 from public.expense_claims claim where claim.tenant_id=expense_lines.tenant_id and claim.id=expense_lines.expense_claim_id));
create policy expense_decisions_visible on public.expense_decisions for select to authenticated using(exists(select 1 from public.expense_claims claim where claim.tenant_id=expense_decisions.tenant_id and claim.id=expense_decisions.expense_claim_id));
commit;