begin;
insert into public.role_permissions(role_key,permission_key)values('TENANT_ADMIN','JOINT_WORK_VIEW_TEAM'),('TENANT_ADMIN','JOINT_WORK_MANAGE'),('MANAGER','JOINT_WORK_VIEW_TEAM'),('MANAGER','JOINT_WORK_MANAGE')on conflict do nothing;
create table public.joint_work_assignments(
 id uuid primary key default extensions.gen_random_uuid(),tenant_id uuid not null references public.tenants(id)on delete cascade,target_employee_id uuid not null,participant_employee_id uuid not null,work_date date not null,status text not null default'PLANNED' check(status in('PLANNED','ACTIVE','COMPLETED')),execution_id uuid,scheduled_by uuid not null,schedule_operation_id uuid not null,joined_at timestamptz,join_operation_id uuid,join_latitude double precision,join_longitude double precision,join_accuracy_meters double precision,left_at timestamptz,leave_operation_id uuid,leave_latitude double precision,leave_longitude double precision,leave_accuracy_meters double precision,created_at timestamptz not null default now(),unique(tenant_id,id),unique(tenant_id,target_employee_id,participant_employee_id,work_date),unique(tenant_id,scheduled_by,schedule_operation_id),unique(tenant_id,participant_employee_id,join_operation_id),unique(tenant_id,participant_employee_id,leave_operation_id),foreign key(tenant_id,target_employee_id)references public.employees(tenant_id,id)on delete restrict,foreign key(tenant_id,participant_employee_id)references public.employees(tenant_id,id)on delete restrict,foreign key(tenant_id,execution_id)references public.tour_executions(tenant_id,id)on delete restrict,foreign key(tenant_id,scheduled_by)references public.tenant_memberships(tenant_id,user_id)on delete restrict,check(target_employee_id<>participant_employee_id));
create or replace function public.admin_schedule_joint_work(p_tenant_id uuid,p_actor uuid,p_operation_id uuid,p_target uuid,p_participant uuid,p_work_date date)returns uuid language plpgsql security definer set search_path='' as $$
declare v_target public.employees%rowtype;v_participant public.employees%rowtype;v_id uuid;v_today date;v_tz text;begin select id into v_id from public.joint_work_assignments where tenant_id=p_tenant_id and scheduled_by=p_actor and schedule_operation_id=p_operation_id;if v_id is not null then return v_id;end if;select employee.*into v_target from public.employees employee where employee.tenant_id=p_tenant_id and employee.id=p_target and employee.status='active';select employee.*into v_participant from public.employees employee where employee.tenant_id=p_tenant_id and employee.id=p_participant and employee.status='active';if v_target.id is null or v_participant.id is null or p_target=p_participant then raise exception'invalid joint-work employees';end if;if not public.user_has_permission(p_tenant_id,p_actor,'JOINT_WORK_MANAGE',v_target.org_unit_id)then raise exception'joint work manage denied';end if;select time_zone into v_tz from public.tenants where id=p_tenant_id;v_today:=(clock_timestamp()at time zone v_tz)::date;if p_work_date<v_today then raise exception'cannot schedule past joint work';end if;insert into public.joint_work_assignments(tenant_id,target_employee_id,participant_employee_id,work_date,scheduled_by,schedule_operation_id)values(p_tenant_id,p_target,p_participant,p_work_date,p_actor,p_operation_id)returning id into v_id;return v_id;end;$$;
create or replace function public.link_joint_work_to_execution()returns trigger language plpgsql security definer set search_path='' as $$begin update public.joint_work_assignments set execution_id=new.id,status='ACTIVE' where tenant_id=new.tenant_id and target_employee_id=new.employee_id and work_date=new.work_date and status='PLANNED';return new;end;$$;
create trigger joint_work_execution_link after insert on public.tour_executions for each row execute function public.link_joint_work_to_execution();
create or replace function public.admin_join_joint_work(p_tenant_id uuid,p_user_id uuid,p_joint_id uuid,p_operation_id uuid,p_lat double precision,p_lon double precision,p_accuracy double precision)returns void language plpgsql security definer set search_path='' as $$
declare v_joint public.joint_work_assignments%rowtype;v_participant_user uuid;begin select joint.*into v_joint from public.joint_work_assignments joint where joint.tenant_id=p_tenant_id and joint.id=p_joint_id for update;if v_joint.id is null or v_joint.execution_id is null or v_joint.status<>'ACTIVE'then raise exception'active joint work not found';end if;select user_id into v_participant_user from public.employees where tenant_id=p_tenant_id and id=v_joint.participant_employee_id and status='active';if v_participant_user is distinct from p_user_id then raise exception'participant identity mismatch';end if;if v_joint.joined_at is not null then if v_joint.join_operation_id=p_operation_id then return;end if;raise exception'joint work already joined';end if;if not exists(select 1 from public.tour_executions execution where execution.tenant_id=p_tenant_id and execution.id=v_joint.execution_id and execution.status='ACTIVE')then raise exception'target tour not active';end if;update public.joint_work_assignments set joined_at=clock_timestamp(),join_operation_id=p_operation_id,join_latitude=p_lat,join_longitude=p_lon,join_accuracy_meters=p_accuracy where tenant_id=p_tenant_id and id=p_joint_id;end;$$;
create or replace function public.admin_leave_joint_work(p_tenant_id uuid,p_user_id uuid,p_joint_id uuid,p_operation_id uuid,p_lat double precision,p_lon double precision,p_accuracy double precision)returns void language plpgsql security definer set search_path='' as $$
declare v_joint public.joint_work_assignments%rowtype;v_participant_user uuid;begin select joint.*into v_joint from public.joint_work_assignments joint where joint.tenant_id=p_tenant_id and joint.id=p_joint_id for update;if v_joint.id is null then raise exception'joint work not found';end if;select user_id into v_participant_user from public.employees where tenant_id=p_tenant_id and id=v_joint.participant_employee_id;if v_participant_user is distinct from p_user_id then raise exception'participant identity mismatch';end if;if v_joint.left_at is not null then if v_joint.leave_operation_id=p_operation_id then return;end if;raise exception'joint work already left';end if;if v_joint.joined_at is null then raise exception'joint work was not joined';end if;update public.joint_work_assignments set left_at=clock_timestamp(),leave_operation_id=p_operation_id,leave_latitude=p_lat,leave_longitude=p_lon,leave_accuracy_meters=p_accuracy,status='COMPLETED'where tenant_id=p_tenant_id and id=p_joint_id;end;$$;
create or replace function public.block_submit_with_open_joint_work()returns trigger language plpgsql security definer set search_path='' as $$begin if old.status='ACTIVE'and new.status='SUBMITTED'and exists(select 1 from public.joint_work_assignments joint where joint.tenant_id=new.tenant_id and joint.execution_id=new.id and joint.joined_at is not null and joint.left_at is null)then raise exception'open joint-work session must be closed before submitting tour';end if;return new;end;$$;
create trigger tour_execution_joint_work_guard before update of status on public.tour_executions for each row execute function public.block_submit_with_open_joint_work();
revoke all on function public.admin_schedule_joint_work(uuid,uuid,uuid,uuid,uuid,date)from public;revoke all on function public.admin_join_joint_work(uuid,uuid,uuid,uuid,double precision,double precision,double precision)from public;revoke all on function public.admin_leave_joint_work(uuid,uuid,uuid,uuid,double precision,double precision,double precision)from public;grant execute on function public.admin_schedule_joint_work(uuid,uuid,uuid,uuid,uuid,date)to service_role;grant execute on function public.admin_join_joint_work(uuid,uuid,uuid,uuid,double precision,double precision,double precision)to service_role;grant execute on function public.admin_leave_joint_work(uuid,uuid,uuid,uuid,double precision,double precision,double precision)to service_role;
alter table public.joint_work_assignments enable row level security;revoke all on public.joint_work_assignments from anon,authenticated;grant select on public.joint_work_assignments to authenticated;
create policy joint_work_visible on public.joint_work_assignments for select to authenticated using(exists(select 1 from public.employees target where target.tenant_id=joint_work_assignments.tenant_id and target.id=joint_work_assignments.target_employee_id and(target.user_id=auth.uid()or public.has_permission(joint_work_assignments.tenant_id,'JOINT_WORK_VIEW_TEAM',target.org_unit_id)))or exists(select 1 from public.employees participant where participant.tenant_id=joint_work_assignments.tenant_id and participant.id=joint_work_assignments.participant_employee_id and participant.user_id=auth.uid()));
commit;