import assert from "node:assert/strict";import test from "node:test";
import {allowedCatalog,canDetail,detailingIntent,isEligible,recordedSessions,type CatalogScope,type CatalogAsset,type ActiveVisit} from "../src/features/clm-library/model.ts";
const scope:CatalogScope={tenantId:"t",authorizedForTenantId:"t",contextKey:"s1",allowedProductIds:["p"],allowedRegions:["IN"],roleCanDetail:true,today:"2026-10-11"};
const asset:CatalogAsset={id:"a",tenantId:"t",productId:"p",regionCode:"IN",title:"Approved",contentType:"application/pdf",version:"v2",status:"APPROVED",approvedBy:"MLR",approvedAt:"2026-10-01T09:00:00Z",effectiveFrom:"2026-10-01",expiresAt:"2026-10-31",provenanceId:"audit-1"};
const visit:ActiveVisit={tenantId:"t",id:"visit",customerId:"doctor",status:"CHECKED_IN",productIds:["p"]};
test("filter tenant, product and region before showing metadata",()=>{const rows=[asset,{...asset,id:"foreign",tenantId:"other"},{...asset,id:"uk",regionCode:"GB"},{...asset,id:"q",productId:"other"}];assert.deepEqual(allowedCatalog(scope,rows),[asset]);assert.deepEqual(allowedCatalog({...scope,authorizedForTenantId:"other"},rows),[]);assert.deepEqual(allowedCatalog({...scope,contextKey:""},rows),[]);});
test("approval status, expiry, effective start and provenance gate use",()=>{assert.equal(isEligible(scope,asset),true);for(const bad of [{...asset,status:"REVOKED" as const},{...asset,expiresAt:"2026-10-10"},{...asset,effectiveFrom:"2026-10-12"},{...asset,approvedBy:""}])assert.equal(isEligible(scope,bad),false);});
test("handoff requires active visit, product match, allowed role and matching tenant",()=>{assert.equal(canDetail(scope,asset,visit),true);assert.equal(detailingIntent(scope,asset,visit)?.activeVisitId,"visit");assert.equal(canDetail(scope,asset,{...visit,status:"CHECKED_OUT"}),false);assert.equal(canDetail(scope,asset,{...visit,productIds:[]}),false);assert.equal(canDetail({...scope,roleCanDetail:false},asset,visit),false);assert.equal(canDetail(scope,asset,{...visit,tenantId:"other"}),false);});
test("session provenance is scoped and sorted by absolute timestamps",()=>{const rows=[{id:"late",tenantId:"t",assetId:"a",assetVersion:"v2",visitId:"v",occurredAt:"2026-10-10T23:30:00-02:00",status:"RECORDED" as const,provenanceId:"x"},{id:"early",tenantId:"t",assetId:"a",assetVersion:"v2",visitId:"v",occurredAt:"2026-10-11T00:30:00Z",status:"RECORDED" as const,provenanceId:"x"},{id:"leak",tenantId:"other",assetId:"a",assetVersion:"v2",visitId:"v",occurredAt:"2026-10-11T10:30:00Z",status:"RECORDED" as const,provenanceId:"x"}];assert.deepEqual(recordedSessions(scope,[asset],rows).map(r=>r.id),["late","early"]);});
