import test from "node:test";import assert from "node:assert/strict";
import {approvedLinks,isAuthorized,safeHistory,visibleSubject,type CustomerRef,type RelationshipEvidence,type ViewerScope,type VisitSummary} from "../src/features/customer-relations/model.ts";
const scope:ViewerScope={tenantId:"a",authorizedForTenantId:"a",contextKey:"login-1",role:"FIELD",permittedTerritoryIds:["north"],mayViewHistory:true,mayOpenSource:false};
const doctor:CustomerRef={tenantId:"a",id:"d1",kind:"doctor",name:"Dr Alpha",territoryId:"north"}, chemist:CustomerRef={tenantId:"a",id:"c1",kind:"chemist",name:"Chemist",territoryId:"north"};
const link:RelationshipEvidence={id:"l1",tenantId:"a",source:{kind:"doctor",id:"d1"},target:{kind:"chemist",id:"c1"},relation:"linked",approval:"APPROVED",evidenceId:"ev1",evidenceType:"CRM",verifiedAt:"2026-10-10T12:00:00Z"};
const history:VisitSummary={id:"v1",tenantId:"a",customerKind:"doctor",customerId:"d1",territoryId:"north",occurredAt:"2026-10-10T23:30:00-02:00",visitType:"CALL",summary:"Follow-up",provenanceId:"audit1",patientSafe:true};
test("tenant, role territory and selected customer are jointly required",()=>{assert.ok(visibleSubject(scope,doctor,[doctor]));assert.equal(visibleSubject({...scope,authorizedForTenantId:"b"},doctor,[doctor]),null);assert.equal(visibleSubject({...scope,permittedTerritoryIds:[]},doctor,[doctor]),null);assert.equal(isAuthorized({...scope,contextKey:""}),false);});
test("only approved relationships with authorized counterpart and provenance",()=>{const links=[link,{...link,id:"pending",approval:"PENDING" as const},{...link,id:"tenant",tenantId:"b"},{...link,id:"missing",evidenceId:""}];assert.deepEqual(approvedLinks(scope,doctor,[doctor,chemist],links).map(x=>x.id),["l1"]);assert.deepEqual(approvedLinks(scope,doctor,[doctor],links),[]);});
test("patient-safe history filters subject, tenant, territory, role, dates and absolute timestamp",()=>{const rows=[history,{...history,id:"v2",occurredAt:"2026-10-11T00:30:00Z"},{...history,id:"unsafe",patientSafe:false},{...history,id:"foreign",tenantId:"b"},{...history,id:"wrong",customerId:"c1"},{...history,id:"nosource",provenanceId:""}];assert.deepEqual(safeHistory(scope,doctor,[doctor],rows).map(x=>x.id),["v1","v2"]);assert.deepEqual(safeHistory({...scope,mayViewHistory:false},doctor,[doctor],rows),[]);assert.equal(safeHistory(scope,doctor,[doctor],rows,"2026-10-12").length,0);});
