import type { RbacService } from "../../rbac/src/index.ts";
export type JointWork={id:string;targetEmployeeId:string;targetOrgUnitId:string;participantEmployeeId:string;workDate:string;status:"PLANNED"|"ACTIVE"|"COMPLETED";executionId:string|null;joinedAt:string|null;leftAt:string|null};
export type JointWorkRepository={listVisible(t:string,token:string):Promise<JointWork[]>;getVisible(t:string,id:string,token:string):Promise<JointWork|null>;schedule(t:string,a:string,input:{operationId:string;targetEmployeeId:string;participantEmployeeId:string;workDate:string}):Promise<string>;join(t:string,u:string,id:string,input:{operationId:string;latitude:number;longitude:number;accuracyMeters:number}):Promise<void>;leave(t:string,u:string,id:string,input:{operationId:string;latitude:number;longitude:number;accuracyMeters:number}):Promise<void>};
export class JointWorkInputError extends Error{};export class JointWorkNotFoundError extends Error{};export class JointWorkConflictError extends Error{};
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i,DATE=/^\d{4}-\d{2}-\d{2}$/;
function uuid(v:unknown,f:string){if(typeof v!=="string"||!UUID.test(v))throw new JointWorkInputError(`${f} must be UUID`);return v}
function date(v:unknown){if(typeof v!=="string"||!DATE.test(v))throw new JointWorkInputError("Invalid workDate");const d=new Date(v+"T00:00:00Z");if(Number.isNaN(d.getTime())||d.toISOString().slice(0,10)!==v)throw new JointWorkInputError("Invalid workDate");return v}
function num(v:unknown,f:string,min:number,max:number){if(typeof v!=="number"||!Number.isFinite(v)||v<min||v>max)throw new JointWorkInputError(`Invalid ${f}`);return v}
function evidence(v:Record<string,unknown>){return{operationId:uuid(v.operationId,"operationId"),latitude:num(v.latitude,"latitude",-90,90),longitude:num(v.longitude,"longitude",-180,180),accuracyMeters:num(v.accuracyMeters,"accuracyMeters",0,1000)}}
export function createJointWorkService(r:JointWorkRepository,rbac:RbacService){return{
 list:(t:string,token:string)=>r.listVisible(t,token),
 async schedule(t:string,a:string,token:string,v:Record<string,unknown>){const target=uuid(v.targetEmployeeId,"targetEmployeeId"),participant=uuid(v.participantEmployeeId,"participantEmployeeId");if(target===participant)throw new JointWorkInputError("Participant must differ from target employee");const id=await r.schedule(t,a,{operationId:uuid(v.operationId,"operationId"),targetEmployeeId:target,participantEmployeeId:participant,workDate:date(v.workDate)});const row=await r.getVisible(t,id,token);if(!row)throw new JointWorkConflictError("Joint work could not be confirmed");return row;},
 async join(t:string,u:string,token:string,idValue:unknown,v:Record<string,unknown>){const id=uuid(idValue,"jointWorkId");await r.join(t,u,id,evidence(v));const row=await r.getVisible(t,id,token);if(!row||!row.joinedAt)throw new JointWorkConflictError("Joint work join could not be confirmed");return row;},
 async leave(t:string,u:string,token:string,idValue:unknown,v:Record<string,unknown>){const id=uuid(idValue,"jointWorkId");await r.leave(t,u,id,evidence(v));const row=await r.getVisible(t,id,token);if(!row||row.status!=="COMPLETED")throw new JointWorkConflictError("Joint work leave could not be confirmed");return row;}
};}
