import type { RbacService } from "../../rbac/src/index.ts";
export const EXPENSE_CATEGORIES=["TRAVEL","MEAL","LODGING","LOCAL_CONVEYANCE","OTHER"] as const;export type ExpenseCategory=typeof EXPENSE_CATEGORIES[number];
export type ExpenseLine={sequence:number;category:ExpenseCategory;amount:number;remarks:string|null;receiptReference:string|null};
export type ExpenseClaim={id:string;executionId:string;employeeId:string;orgUnitId:string;workDate:string;currencyCode:string;status:"DRAFT"|"SUBMITTED"|"APPROVED"|"REJECTED"|"RETURNED";totalAmount:number;submissionComment:string|null;reviewComment:string|null;lines:ExpenseLine[]};
export type ExpenseRepository={listVisible(t:string,token:string,pending?:boolean):Promise<ExpenseClaim[]>;listOwn(t:string,u:string,token:string):Promise<ExpenseClaim[]>;getVisible(t:string,id:string,token:string):Promise<ExpenseClaim|null>;save(t:string,u:string,executionId:string,input:{operationId:string;currencyCode:string;lines:ExpenseLine[]}):Promise<string>;submit(t:string,u:string,id:string,input:{operationId:string;comment:string|null}):Promise<void>;decide(t:string,a:string,id:string,decision:"APPROVE"|"REJECT"|"RETURN",comment:string|null):Promise<void>};
export class ExpenseInputError extends Error{};export class ExpenseNotFoundError extends Error{};export class ExpenseConflictError extends Error{};
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
function uuid(v:unknown,f:string){if(typeof v!=="string"||!UUID.test(v))throw new ExpenseInputError(`${f} must be UUID`);return v}
function txt(v:unknown,f:string,max:number,required=false){if(v==null||v===""){if(required)throw new ExpenseInputError(`${f} required`);return null}if(typeof v!=="string")throw new ExpenseInputError(`Invalid ${f}`);const s=v.trim();if(!s||s.length>max)throw new ExpenseInputError(`Invalid ${f}`);return s}
function lines(v:unknown):ExpenseLine[]{if(!Array.isArray(v)||v.length<1||v.length>50)throw new ExpenseInputError("lines must contain 1 to 50 entries");const seq=new Set<number>();return v.map((raw,i)=>{if(!raw||typeof raw!=="object"||Array.isArray(raw))throw new ExpenseInputError(`Invalid line ${i}`);const x=raw as Record<string,unknown>;if(!Number.isInteger(x.sequence)||(x.sequence as number)<1||seq.has(x.sequence as number))throw new ExpenseInputError("Invalid/duplicate sequence");seq.add(x.sequence as number);if(typeof x.category!=="string"||!EXPENSE_CATEGORIES.includes(x.category as ExpenseCategory))throw new ExpenseInputError("Invalid category");if(typeof x.amount!=="number"||!Number.isFinite(x.amount)||x.amount<=0||x.amount>10000000)throw new ExpenseInputError("Invalid amount");return{sequence:x.sequence as number,category:x.category as ExpenseCategory,amount:Math.round(x.amount*100)/100,remarks:txt(x.remarks,"remarks",500),receiptReference:txt(x.receiptReference,"receiptReference",300)}}).sort((a,b)=>a.sequence-b.sequence)}
function currency(v:unknown){if(typeof v!=="string"||!/^[A-Z]{3}$/.test(v))throw new ExpenseInputError("currencyCode must be 3 uppercase letters");return v}
export function createExpenseService(r:ExpenseRepository,rbac:RbacService){return{
 list:(t:string,token:string)=>r.listVisible(t,token,false),listOwn:(t:string,u:string,token:string)=>r.listOwn(t,u,token),listPending:(t:string,token:string)=>r.listVisible(t,token,true),
 async get(t:string,token:string,idValue:unknown){const row=await r.getVisible(t,uuid(idValue,"claimId"),token);if(!row)throw new ExpenseNotFoundError("Expense claim not found");return row;},
 async save(t:string,u:string,token:string,executionValue:unknown,v:Record<string,unknown>){const id=await r.save(t,u,uuid(executionValue,"executionId"),{operationId:uuid(v.operationId,"operationId"),currencyCode:currency(v.currencyCode),lines:lines(v.lines)});const row=await r.getVisible(t,id,token);if(!row)throw new ExpenseConflictError("Expense claim could not be confirmed");return row;},
 async submit(t:string,u:string,token:string,idValue:unknown,v:Record<string,unknown>){const id=uuid(idValue,"claimId");await r.submit(t,u,id,{operationId:uuid(v.operationId,"operationId"),comment:txt(v.comment,"comment",1000)});const row=await r.getVisible(t,id,token);if(!row||row.status!=="SUBMITTED")throw new ExpenseConflictError("Submitted expense claim could not be confirmed");return row;},
 async decide(t:string,a:string,token:string,idValue:unknown,v:Record<string,unknown>){const id=uuid(idValue,"claimId");const row=await r.getVisible(t,id,token);if(!row)throw new ExpenseNotFoundError("Expense claim not found");if(row.status!=="SUBMITTED")throw new ExpenseConflictError("Only submitted claims can be reviewed");if(v.decision!=="APPROVE"&&v.decision!=="REJECT"&&v.decision!=="RETURN")throw new ExpenseInputError("Invalid decision");const c=txt(v.comment,"comment",1000,v.decision!=="APPROVE");await rbac.authorize(t,"EXPENSE_APPROVE",row.orgUnitId,token);await r.decide(t,a,id,v.decision,c);}
};}
