import type { RbacService } from "../../rbac/src/index.ts";
export type LeaveRequest={id:string;employeeId:string;orgUnitId:string;leaveType:"FULL_DAY"|"HALF_DAY";startDate:string;endDate:string;reason:string;status:"SUBMITTED"|"APPROVED"|"REJECTED";managerComment:string|null;reviewedAt:string|null};
export type AttendanceRow={workDate:string;status:"WORKING"|"PRESENT"|"SHORT_DAY"|"LEAVE"|"HALF_DAY_LEAVE";workedMinutes:number|null;requiredMinutes:number|null;shortDayReason:string|null;leaveRequestId:string|null};
export type AttendanceLeaveRepository={listAttendance(t:string,token:string):Promise<AttendanceRow[]>;listVisibleLeaves(t:string,token:string,pendingOnly?:boolean):Promise<LeaveRequest[]>;listOwnLeaves(t:string,u:string,token:string):Promise<LeaveRequest[]>;getLeave(t:string,id:string,token:string):Promise<LeaveRequest|null>;submitLeave(t:string,u:string,input:{operationId:string;leaveType:"FULL_DAY"|"HALF_DAY";startDate:string;endDate:string;reason:string}):Promise<string>;decideLeave(t:string,a:string,id:string,decision:"APPROVE"|"REJECT",comment:string|null):Promise<void>};
export class LeaveInputError extends Error{};export class LeaveNotFoundError extends Error{};export class LeaveConflictError extends Error{};
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i,DATE=/^\d{4}-\d{2}-\d{2}$/;
function uuid(v:unknown,f:string){if(typeof v!=="string"||!UUID.test(v))throw new LeaveInputError(`${f} must be UUID`);return v}
function date(v:unknown,f:string){if(typeof v!=="string"||!DATE.test(v))throw new LeaveInputError(`Invalid ${f}`);const d=new Date(`${v}T00:00:00Z`);if(Number.isNaN(d.getTime())||d.toISOString().slice(0,10)!==v)throw new LeaveInputError(`Invalid ${f}`);return v}
function txt(v:unknown,f:string,max:number,required=true){if(v==null||v===""){if(required)throw new LeaveInputError(`${f} required`);return null}if(typeof v!=="string")throw new LeaveInputError(`Invalid ${f}`);const s=v.trim();if(!s||s.length>max)throw new LeaveInputError(`Invalid ${f}`);return s}
export function createAttendanceLeaveService(r:AttendanceLeaveRepository,rbac:RbacService){return{
 listAttendance:(t:string,token:string)=>r.listAttendance(t,token),listLeaves:(t:string,token:string)=>r.listVisibleLeaves(t,token,false),listOwnLeaves:(t:string,u:string,token:string)=>r.listOwnLeaves(t,u,token),listPending:(t:string,token:string)=>r.listVisibleLeaves(t,token,true),
 async submit(t:string,u:string,token:string,v:Record<string,unknown>){if(v.leaveType!=="FULL_DAY"&&v.leaveType!=="HALF_DAY")throw new LeaveInputError("Invalid leaveType");const start=date(v.startDate,"startDate"),end=date(v.endDate,"endDate");const days=(new Date(end+"T00:00:00Z").getTime()-new Date(start+"T00:00:00Z").getTime())/86400000+1;if(days<1||days>31)throw new LeaveInputError("Leave range must be 1 to 31 days");if(v.leaveType==="HALF_DAY"&&days!==1)throw new LeaveInputError("Half-day leave must be a single date");const id=await r.submitLeave(t,u,{operationId:uuid(v.operationId,"operationId"),leaveType:v.leaveType,startDate:start,endDate:end,reason:txt(v.reason,"reason",1000)!});const row=await r.getLeave(t,id,token);if(!row)throw new LeaveConflictError("Leave request could not be confirmed");return row;},
 async decide(t:string,a:string,token:string,idValue:unknown,v:Record<string,unknown>){const id=uuid(idValue,"leaveId");const row=await r.getLeave(t,id,token);if(!row)throw new LeaveNotFoundError("Leave request not found");if(row.status!=="SUBMITTED")throw new LeaveConflictError("Only submitted leave can be reviewed");if(v.decision!=="APPROVE"&&v.decision!=="REJECT")throw new LeaveInputError("Invalid decision");const c=txt(v.comment,"comment",1000,v.decision==="REJECT");await rbac.authorize(t,"LEAVE_APPROVE",row.orgUnitId,token);await r.decideLeave(t,a,id,v.decision,c);}
};}
